# Site settings
title: Andrés Montenegro | Software Developer
description: Andrés Montenegro | Software Developer
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andrés Montenegro
user_description: Software Developer with experience
user_title: Software Developer
email: andresmontenegroarguello@gmail.com
twitter_username: AndresMSoftware
github_username:  andresmontenegroarguello
gplus_username:  117141258615251096772
facebok_username: 
# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
